export const MOVIES_LIST_REQUEST = "MOVIES_LIST_REQUEST";
export const MOVIES_LIST_SUCCESS = "MOVIES_LIST_SUCCESS";
export const MOVIES_LIST_FAIL = "MOVIES_LIST_FAIL";
export const MOVIES_LIST_RESET = "MOVIES_LIST_RESET";

export const MOVIES_RANDOM_REQUEST = "MOVIES_RANDOM_REQUEST";
export const MOVIES_RANDOM_SUCCESS = "MOVIES_RANDOM_SUCCESS";
export const MOVIES_RANDOM_FAIL = "MOVIES_RANDOM_FAIL";
export const MOVIES_RANDOM_RESET = "MOVIES_RANDOM_RESET";

export const MOVIES_BY_ID_REQUEST = "MOVIES_BY_ID_REQUEST";
export const MOVIES_BY_ID_SUCCESS = "MOVIES_BY_ID_SUCCESS";
export const MOVIES_BY_ID_FAIL = "MOVIES_BY_ID_FAIL";
export const MOVIES_BY_ID_RESET = "MOVIES_BY_ID_RESET";

export const MOVIES_TOP_RATED_REQUEST = "MOVIES_TOP_RATED_REQUEST";
export const MOVIES_TOP_RATED_SUCCESS = "MOVIES_TOP_RATED_SUCCESS";
export const MOVIES_TOP_RATED_FAIL = "MOVIES_TOP_RATED_FAIL";
export const MOVIES_TOP_RATED_RESET = "MOVIES_TOP_RATED_RESET";

export const ADD_MOVIE_REVIEW_REQUEST = "ADD_MOVIE_REVIEW_REQUEST";
export const ADD_MOVIE_REVIEW_SUCCESS = "ADD_MOVIE_REVIEW_SUCCESS";
export const ADD_MOVIE_REVIEW_FAIL = "ADD_MOVIE_REVIEW_FAIL";
export const ADD_MOVIE_REVIEW_RESET = "ADD_MOVIE_REVIEW_RESET";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";
export const DELETE_MOVIE_RESET = "DELETE_MOVIE_RESET";

export const DELETE_ALL_MOVIES_REQUEST = "DELETE_ALL_MOVIES_REQUEST";
export const DELETE_ALL_MOVIES_SUCCESS = "DELETE_ALL_MOVIES_SUCCESS";
export const DELETE_ALL_MOVIES_FAIL = "DELETE_ALL_MOVIES_FAIL";
export const DELETE_ALL_MOVIES_RESET = "DELETE_ALL_MOVIES_RESET";

export const ADD_MOVIE_REQUEST = "ADD_MOVIE_REQUEST";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAIL = "ADD_MOVIE_FAIL";
export const ADD_MOVIE_RESET = "ADD_MOVIE_RESET";

export const ADD_CAST = "ADD_CAST";
export const EDIT_CAST = "EDIT_CAST";
export const DELETE_CAST = "DELETE_CAST";
export const RESET_CAST = "RESET_CAST";
