export const MOVIES_LIST_REQUEST = "MOVIES_LIST_REQUEST";
export const MOVIES_LIST_SUCCESS = "MOVIES_LIST_SUCCESS";
export const MOVIES_LIST_FAIL = "MOVIES_LIST_FAIL";
export const MOVIES_LIST_RESET = "MOVIES_LIST_RESET";

export const MOVIES_RANDOM_REQUEST = "MOVIES_RANDOM_REQUEST";
export const MOVIES_RANDOM_SUCCESS = "MOVIES_RANDOM_SUCCESS";
export const MOVIES_RANDOM_FAIL = "MOVIES_RANDOM_FAIL";
export const MOVIES_RANDOM_RESET = "MOVIES_RANDOM_RESET";

export const MOVIES_BY_ID_REQUEST = "MOVIES_BY_ID_REQUEST";
export const MOVIES_BY_ID_SUCCESS = "MOVIES_BY_ID_SUCCESS";
export const MOVIES_BY_ID_FAIL = "MOVIES_BY_ID_FAIL";
export const MOVIES_BY_ID_RESET = "MOVIES_BY_ID_RESET";

export const MOVIES_TOP_RATED_REQUEST = "MOVIES_TOP_RATED_REQUEST";
export const MOVIES_TOP_RATED_SUCCESS = "MOVIES_TOP_RATED_SUCCESS";
export const MOVIES_TOP_RATED_FAIL = "MOVIES_TOP_RATED_FAIL";
export const MOVIES_TOP_RATED_RESET = "MOVIES_TOP_RATED_RESET";

export const ADD_MOVIE_REVIEW_REQUEST = "ADD_MOVIE_REVIEW_REQUEST";
export const ADD_MOVIE_REVIEW_SUCCESS = "ADD_MOVIE_REVIEW_SUCCESS";
export const ADD_MOVIE_REVIEW_FAIL = "ADD_MOVIE_REVIEW_FAIL";
export const ADD_MOVIE_REVIEW_RESET = "ADD_MOVIE_REVIEW_RESET";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";
export const DELETE_MOVIE_RESET = "DELETE_MOVIE_RESET";

export const DELETE_ALL_MOVIES_REQUEST = "DELETE_ALL_MOVIES_REQUEST";
export const DELETE_ALL_MOVIES_SUCCESS = "DELETE_ALL_MOVIES_SUCCESS";
export const DELETE_ALL_MOVIES_FAIL = "DELETE_ALL_MOVIES_FAIL";
export const DELETE_ALL_MOVIES_RESET = "DELETE_ALL_MOVIES_RESET";

export const ADD_MOVIE_REQUEST = "ADD_MOVIE_REQUEST";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAIL = "ADD_MOVIE_FAIL";
export const ADD_MOVIE_RESET = "ADD_MOVIE_RESET";

export const ADD_CAST = "ADD_CAST";
export const EDIT_CAST = "EDIT_CAST";
export const DELETE_CAST = "DELETE_CAST";
export const RESET_CAST = "RESET_CAST";

export const UPDATE_MOVIE_REQUEST = "UPDATE_MOVIE_REQUEST";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";
export const UPDATE_MOVIE_RESET = "UPDATE_MOVIE_RESET";

export const MOVIE_GENRE_REQUEST = "MOVIE_GENRE_REQUEST";
export const MOVIE_GENRE_SUCCESS = "MOVIE_GENRE_SUCCESS";
export const MOVIE_GENRE_FAIL = "MOVIE_GENRE_FAIL";
export const MOVIE_GENRE_RESET = "MOVIE_GENRE_RESET";

export const MOVIE_LANG_REQUEST = "MOVIE_LANG_REQUEST";
export const MOVIE_LANG_SUCCESS = "MOVIE_LANG_SUCCESS";
export const MOVIE_LANG_FAIL = "MOVIE_LANG_FAIL";
export const MOVIE_LANG_RESET = "MOVIE_LANG_RESET";


export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const APPLY_FILTERS = "APPLY_FILTERS";